version: '3.7'

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=blogDB
    volumes:
      - blogDB_pg_data:/var/lib/postgresql/data

volumes:
  blogDB_pg_data: